# Generated by Django 4.2.1 on 2023-05-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
